{% set version = "3.5.1" %}


package:
  name: assimulo
  version: {{ version }}

source:
  url: https://github.com/modelon-community/Assimulo/archive/refs/tags/Assimulo-{{ version }}.tar.gz
  sha256: 356a78953f13172f64fd040aceda7c00216e99766ac0758eaaec07d5fdf394f7
  patches:
    # ld: cannot find -lblas_OPENMP
    - link.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - libblas
    - liblapack
    - python <3.12
    - pip
    - numpy
    - cython
    - sundials
  run:
    - python <3.12
    - {{ pin_compatible('numpy') }}
    - scipy
    - sundials

test:
  imports:
    - assimulo
    - assimulo.solvers
    - assimulo.solvers.euler
    - assimulo.solvers.odepack
  requires:
    - nose
  files:
    - cvode_basic.py
    - cvode_with_jac_sparse.py
  commands:
    - python cvode_basic.py
    - python cvode_with_jac_sparse.py

about:
  home: https://github.com/modelon-community/Assimulo
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
