{% set version = "3.4.1" %}


package:
  name: assimulo
  version: {{ version }}

source:
  url: https://github.com/modelon-community/Assimulo/archive/refs/tags/Assimulo-{{ version }}.tar.gz
  sha256: 75ff22d5bdae40972676d12c09f00a32835346341df9973688243e4f008583c0
  patches:
    # ld: cannot find -lblas_OPENMP
    - link.patch
    # call to undeclared function 'SUNSuperLUMT'
    - slu6.patch
    # blas detection
    - check_blas.patch

build:
  number: 5

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - make  # [unix]
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - libblas
    - liblapack
    - python
    - pip
    - numpy
    - cython <3
    - sundials
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - sundials

test:
  imports:
    - assimulo
    - assimulo.solvers
    - assimulo.solvers.euler
    - assimulo.solvers.odepack
  requires:
    - nose
  files:
    - cvode_basic.py
    - cvode_with_jac_sparse.py
  commands:
    - python cvode_basic.py
    - python cvode_with_jac_sparse.py

about:
  home: https://github.com/modelon-community/Assimulo
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
