{% set version = "3.0" %}

package:
  name: assimulo
  version: {{ version }}

source:
  url: https://github.com/modelon/Assimulo/archive/Assimulo-{{ version }}.tar.gz
  sha256: 6a1437af8ea0c9af3c0afa1efb44f5d1e11edfec1250ce3510f9e33397a04e6b
  patches:
    # find blas with dynamic extension
    - blas_shared.patch
    # https://github.com/modelon/Assimulo/pull/3
    - 0001-Dont-output-to-stdout-on-solver-ImportError.patch

build:
  number: 1007

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('c') }}
  host:
    - msinttypes  # [win and py27]
    - libblas  # [unix]
    - liblapack  # [unix]
    - python
    - pip
    - numpy
    - cython
    - sundials
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - sundials

test:
  imports:
    - assimulo
    - assimulo.solvers
    - assimulo.examples
  requires:
    - nose

about:
  home: http://www.jmodelica.org/assimulo
  license: LGPL
  license_file: LICENSE
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
