{% set version = "3.3" %}


package:
  name: assimulo
  version: {{ version }}

source:
  url: https://github.com/modelon-community/Assimulo/archive/refs/tags/Assimulo-{{ version }}.tar.gz
  sha256: 871741bf8314deb6860570011f1d095f7fa56bcad9bc60d4860f1e951b57f179

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - libblas
    - liblapack
    - python
    - pip
    - numpy
    - cython
    - sundials
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - sundials

test:
  imports:
    - assimulo
    - assimulo.solvers
    - assimulo.solvers.euler
    - assimulo.solvers.odepack
  requires:
    - nose

about:
  home: http://www.jmodelica.org/assimulo
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
