{% set version = "3.7.3" %}


package:
  name: assimulo
  version: {{ version }}

source:
  url: https://github.com/modelon-community/Assimulo/archive/refs/tags/Assimulo-{{ version }}.tar.gz
  sha256: b12d04b4fb0a41e68247731a695be5b31b064db2006ec1d650cdd6816e9dd610
  patches:
    # ld: cannot find -lblas_OPENMP
    - link.patch
    # disable numpy.distutils as its deprecated and fails to build
    - no_distutils.patch

build:
  number: 0
  skip: true  # [python_impl == 'pypy' or ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - libblas
    - liblapack
    - python
    - pip
    - numpy
    - cython
    - sundials
  run:
    - python
    - scipy
    - sundials

test:
  imports:
    - assimulo
    - assimulo.solvers
    - assimulo.solvers.euler
  commands:
    - python -c "from assimulo.examples import cvode_basic; cvode_basic.run_example(with_plots=False)"
    - python -c "from assimulo.examples import cvode_with_jac_sparse; cvode_with_jac_sparse.run_example(with_plots=False)"

about:
  home: https://github.com/modelon-community/Assimulo
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
