{% set version = "2.9" %}

package:
  name: assimulo
  version: {{ version }}

source:
  fn: Assimulo-{{ version }}.zip
  url: https://pypi.io/packages/source/A/Assimulo/Assimulo-{{ version }}.zip
  md5: 3f28fd98011d2ec7a01703a1ef1dff45
  patches:
    # no fortran compiler on windows, unsupported on osx
    - disable-fortran-extensions.patch  # [win or osx]
    # avoid Glimda print to stdout
    - glimda-stderr.patch

build:
  number: 6
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python
    - numpy 1.9.*  # [not (win and py36)]
    - numpy 1.11.*  # [win and py36]
    - cython
    - sundials 2.7.*
    - gcc  # [unix]
  run:
    - python
    - numpy >=1.9  # [not (win and py36)]
    - numpy >=1.11  # [win and py36]
    - scipy
    - matplotlib
    - sundials 2.7.*
    - libgcc  # [unix]

test:
  imports:
    - assimulo
    - assimulo.solvers
  requires:
    - nose

about:
  home: http://www.jmodelica.org/assimulo
  license: LGPL3
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
