{% set version = "3.2" %}

package:
  name: assimulo
  version: {{ version }}

source:
  git_url: https://github.com/modelon-community/Assimulo.git
  git_rev: 98af29e5d4e310524e4c0eafcb5b69276b29dfaf
  patches:
    # find blas with dynamic extension
    - blas_shared.patch  # [unix]
    # sundials 5.x
    - sundials5.patch  # [unix]

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - libblas
    - liblapack
    - python
    - pip
    - numpy
    - cython
    - sundials
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - sundials

test:
  imports:
    - assimulo
    - assimulo.solvers
  requires:
    - nose

about:
  home: http://www.jmodelica.org/assimulo
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
