{% set version = "2.9" %}

package:
  name: assimulo
  version: {{ version }}

source:
  fn: Assimulo-{{ version }}.zip
  url: https://pypi.io/packages/source/A/Assimulo/Assimulo-{{ version }}.zip
  sha256: e61f5278618f3c2c920c0ef758eae0ae9a0538240d0ceaaae06b5dadff35aa2e
  patches:
    # no fortran compiler on vc9, unsupported on osx
    - disable-fortran-extensions.patch  # [osx]

    # sundials 3.1 support: https://trac.jmodelica.org/assimulo/changeset/845
    - r831.patch  # [unix]
    - r833.patch  # [unix]
    - r836.patch  # [unix]
    - r837.patch  # [unix]
    - r838.patch  # [unix]
    - r839.patch  # [unix]
    - r840.patch  # [unix]
    - r841.patch  # [unix]
    - r845.patch  # [unix]

build:
  number: 1008

requirements:
  build:
    - {{ compiler('fortran') }}  # [linux]
    - {{ compiler('c') }}
  host:
    - msinttypes  # [win and py27]
    - python
    - numpy
    - cython
    - sundials
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - sundials

test:
  imports:
    - assimulo
    - assimulo.solvers
  requires:
    - nose

about:
  home: http://www.jmodelica.org/assimulo
  license: LGPL3
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
