{% set version = "3.0" %}

package:
  name: assimulo
  version: {{ version }}

source:
  fn: Assimulo-{{ version }}.tar.gz
  url: https://github.com/modelon/Assimulo/archive/Assimulo-{{ version }}.tar.gz
  sha256: 6a1437af8ea0c9af3c0afa1efb44f5d1e11edfec1250ce3510f9e33397a04e6b
  patches:
    # find blas with dynamic extension
    - blas_shared.patch

build:
  number: 1002

requirements:
  build:
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('c') }}
  host:
    - msinttypes  # [win and py27]
    - python
    - pip
    - numpy
    - cython
    - sundials 3.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - sundials 3.*

test:
  imports:
    - assimulo
    - assimulo.solvers
    - assimulo.examples
  requires:
    - nose

about:
  home: http://www.jmodelica.org/assimulo
  license: LGPL
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
