{% set version = "3.7.0" %}


package:
  name: assimulo
  version: {{ version }}

source:
  url: https://github.com/modelon-community/Assimulo/archive/refs/tags/Assimulo-{{ version }}.tar.gz
  sha256: 26750865071094ca12efbf20ed805e1f160b0adcaa4bfebace2969eb16b77d9c
  patches:
    # ld: cannot find -lblas_OPENMP
    - link.patch
    # disable numpy.distutils as its deprecated and fails to build
    - no_distutils.patch

build:
  number: 0
  skip: true  # [python_impl == 'pypy' or ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - libblas
    - liblapack
    - python
    - pip
    - numpy
    - cython
    - sundials
  run:
    - python
    - scipy
    - sundials

test:
  imports:
    - assimulo
    - assimulo.solvers
    - assimulo.solvers.euler
  files:
    - cvode_basic.py
    - cvode_with_jac_sparse.py
  commands:
    - python cvode_basic.py
    - python cvode_with_jac_sparse.py

about:
  home: https://github.com/modelon-community/Assimulo
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
