{% set version = "2.9" %}

package:
  name: assimulo
  version: {{ version }}

source:
  fn: Assimulo-{{ version }}.zip
  url: https://pypi.io/packages/source/A/Assimulo/Assimulo-{{ version }}.zip
  sha256: e61f5278618f3c2c920c0ef758eae0ae9a0538240d0ceaaae06b5dadff35aa2e
  patches:
    # no fortran compiler on vc9, unsupported on osx
    - disable-fortran-extensions.patch  # [osx]
    # avoid Glimda print to stdout
    - glimda-stderr.patch

build:
  number: 7

requirements:
  build:
    - {{ compiler('fortran') }}  # [linux]
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - cython
    - sundials 2.7.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - sundials 2.7.*

test:
  imports:
    - assimulo
    - assimulo.solvers
  requires:
    - nose

about:
  home: http://www.jmodelica.org/assimulo
  license: LGPL3
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
