{% set version = "2.9" %}

package:
  name: assimulo
  version: {{ version }}

source:
  fn: Assimulo-{{ version }}.zip
  url: https://pypi.io/packages/source/A/Assimulo/Assimulo-{{ version }}.zip
  md5: 3f28fd98011d2ec7a01703a1ef1dff45
  patches:
    # no fortran compiler on windows, unsupported on osx
    - disable-fortran-extensions.patch  # [win or osx]
    # avoid Glimda print to stdout
    - glimda-stderr.patch

build:
  number: 7

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - numpy        # [not (win and py36)]
    - numpy         # [win and py36]
    - cython
    - sundials
  run:
    - python
    - {{ pin_compatible('numpy') }}   # [not (win and py36)]
    - {{ pin_compatible('numpy') }}   # [win and py36]
    - scipy
    - matplotlib
    - sundials

test:
  imports:
    - assimulo
    - assimulo.solvers
  requires:
    - nose

about:
  home: http://www.jmodelica.org/assimulo
  license: LGPL3
  summary: A package for solving ordinary differential equations and differential algebraic equations.

extra:
  recipe-maintainers:
    - chria
    - jschueller
