travis:
  secure:
    BINSTAR_TOKEN: LA9C5zApNSDvLHOWNwJKM5QDAYMhh2LShHM21a4a72fw3FI3o7zoL+gB8VUQAeLjLeuXUs3lNbqNo7iS3ex/cwIfE/Dyx24dlDFPpl/azRaxttthMu2wfgMpkUtHvwOnnW+WxqbMRReJUPZjCZFbC9aiOEAEFZRRiwO4Bprn7RXuFUdhLGJeu4gtGN6xMDTyhq3lP9MwxAt7uMbSNYQukDdJMR4G1+MX6hrfL8h99SLzgm+rFwLUTSftd72bOMGgyxfHIUp1/qX6/FLnTRsxZ+VavdMK5iia0ZtR6zQiDWZSJFMo582jBbAnfKtJfrGEzGQUoZum8RTAcJx2FLa5svuTbcD5eBNYfkSvS3TyQYFmjp3dTLc2af5gEoSh0IhPGlIufIyw2whb93eeRvng6JW6bXZfydctsf3GERSXGRSw1/RtQVV86xZNSCalG2X+gbMfWvKxQXbm03Wxt6ne6lxFl7bw/eddcx2Ne7oAxutIRcEN2z4YnLwD224iNP3/H8UTC7NvH3jkEh5LIhK9ulDJnj0QtUDkMn4MpdrGcwVrOZrrR5oHdszVWxf1ZV6WcsVLSMUtnWZ8Is1RowrkziLIosxsEdDvs0TQR13G4jx5de5wiE89Xp0YTNG2fyDLusOQipxU7jujyhy4YST+IuyJSjEW4lO7PNViUhP3TEw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
